language: cpp
sudo: enabled
dist: trusty
compiler: g++

install:
  - which cmake || sudo apt-get install cmake
  - which lcov || sudo apt-get install lcov

before_script:
  - export CXX=${COMPILER}

script:
  - cd ${TRAVIS_BUILD_DIR}
  - cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Debug
  - cd build
  - make -j

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - ./build/test/TestRobotFramework
  - lcov --capture --directory . --base-directory ${TRAVIS_BUILD_DIR} --output-file coverage.info --no-external
  - lcov --remove coverage.info ${TRAVIS_BUILD_DIR}'test/*' --output-file coverage.info
  - lcov --list coverage.info
  - bash <(curl -s https://codecov.io/bash)