language: cpp
sudo: enabled
dist: trusty
compiler: g++

before_install:
  - pip install --user cpp-coveralls

install:
  - which cmake || sudo apt-get install cmake
  - which lcov || sudo apt-get install lcov

before_script:
  - export CXX=${COMPILER}
  - cd ${TRAVIS_BUILD_DIR}
  - cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Debug
  - cd build

script:
  - make -j
  - make TestRobotFramework_coverage -j

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - coveralls --exclude modules --exclude build --exclude test --gcov-options '\-lp'