language: cpp
sudo: enabled
dist: trusty
compiler: g++

before_install:
  - pip install --user cpp-coveralls

install:
  - which cmake || sudo apt-get install cmake

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - make -j
  - make TestRobotFramework_coverage -j